# Leka - iOS Monorepo
# Copyright 2023 APF Frdance handicap
# SPDX-License-Identifier: Apache-2.0

# auto update fastlane
update_fastlane

default_platform(:ios)

platform :ios do

  desc "Placeholder lane to make sure fastlane's working"
  lane :helloworld do
    puts "Hello, Fastlane!"
  end

end
