# Leka - iOS Monorepo
# Copyright APF France handicap
# SPDX-License-Identifier: Apache-2.0

uuid: 572F710A05F94F25831FF05938728453
icon: sun.rain
color: 0x90CAF9

l10n:
  - locale: fr_FR
    details:
      title: Météo et environnement
      subtitle:
      description:
  - locale: en_US
    details:
      title: Weather and environment
      subtitle:
      description:

content:
  - component: vertical_content_list
    l10n:
      - locale: fr_FR
        details:
          title: Météo et environnement
          subtitle:
          description:
      - locale: en_US
        details:
          title: Weather and environment
          subtitle:
          description:
    items:
      - value: curriculum_leka_weather_robot-ED4C900D4ACB426384DC76F182BC19A5
        type: curriculum
      - value: curriculum_recognition_weather_and_time-1D8E1AB667DB40B199479D731EF96F2E
        type: curriculum
