# Leka - iOS Monorepo
# Copyright 2023 APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Fastlane - Internal Beta Release

on:
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TUIST_TURN_OFF_LINTERS: TRUE
  APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets. APP_STORE_CONNECT_API_KEY_CONTENT }}
  APP_STORE_CONNECT_ISSUER_ID: ${{ secrets. APP_STORE_CONNECT_ISSUER_ID }}
  APP_STORE_CONNECT_API_KEY_ID: ${{ secrets. APP_STORE_CONNECT_API_KEY_ID }}
  FASTLANE_KEYCHAIN_PASSWORD: ${{ secrets.FASTLANE_KEYCHAIN_PASSWORD }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}

jobs:
  internal_beta_release:
    if: contains(github.event.label.name, 'fastlane:rbi')
    name: fastlane release beta_internal
    runs-on: [self-hosted, iOS]

    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 # shallow clone

      - name: bundle install
        run: |
          bundle install

      - name: tuist fetch
        run: |
          tuist fetch

      - name: fastlane helloworld
        run: |
          bundle exec fastlane helloworld

      - name: fastlane sync_certificates
        run: |
          bundle exec fastlane sync_certificates release:true --verbose

      - name: fastlane beta_internal LekaApp
        if: contains(github.event.label.name, 'LekaApp')
        run: |
          bundle exec fastlane beta_internal targets:LekaApp --verbose

      - name: fastlane beta_internal LekaActivityUIExplorer
        if: contains(github.event.label.name, 'LekaActivityUIExplorer')
        run: |
          bundle exec fastlane beta_internal targets:LekaActivityUIExplorer --verbose

      - name: fastlane beta_internal LekaUpdater
        if: contains(github.event.label.name, 'LekaUpdater')
        run: |
          bundle exec fastlane beta_internal targets:LekaUpdater --verbose

      - name: fastlane beta_internal all
        if: contains(github.event.label.name, 'all')
        run: |
          bundle exec fastlane beta_internal targets:all --verbose

      - name: remove label
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { LABEL_NAME } = process.env
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: LABEL_NAME
            })
        env:
          LABEL_NAME: ${{ github.event.label.name }}
