# Leka - iOS Monorepo
# Copyright APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Linter - SwiftFormat

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.swift"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: swiftformat
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        files: [changed_files, all_files]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: false

      - name: Install SwiftFormat
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install swiftformat
          swiftformat --version

      - name: Run swiftformat on ${{ matrix.files }}
        if: matrix.files == 'all_files'
        run: |
          swiftformat --lint --reporter github-actions-log .

      - name: Run swiftformat on ${{ matrix.files }}
        if: matrix.files == 'changed_files'
        run: |
          swiftformat --lint --reporter github-actions-log $(git diff --name-only -r HEAD^1 HEAD --diff-filter=AMCR)
