# Leka - iOS Monorepo
# Copyright 2023 APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: License Checker

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  license_checker:
    name: License Checker
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Check licenses in all files
        run: |
          deno run --allow-read https://deno.land/x/license_checker@v3.2.2/main.ts
