# Leka - iOS Monorepo
# Copyright APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Linter - License Checker

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  license_checker:
    name: lint
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: false

      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Check licenses in all files
        run: |
          deno run --allow-read jsr:@kt3k/license-checker@3.3.1/main
