# Leka - iOS Monorepo
# Copyright APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Linter - SwiftFormat

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.swift"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: swiftformat
    runs-on: [ubuntu-24.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          version: 2024.12.4
          install: true
          cache: true

      - name: Run swiftformat
        run: |
          echo ""
          echo "🏃‍♂️ Running swiftformat"

          which swiftformat
          swiftformat --version

          git diff origin/develop --name-only --diff-filter=AMCR \
            | grep -E "\.swift\$$"                            \
            || echo "No files added nor modified!"

          git diff origin/develop --name-only --diff-filter=AMCR \
            | grep -E "\.swift\$$"                            \
            | xargs --no-run-if-empty swiftformat --lint --reporter github-actions-log --verbose
