# Leka - iOS Monorepo
# Copyright APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Linter - SwiftLint

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: swiftlint
    runs-on: [self-hosted, iOS]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          lfs: true

      - name: Run swiftlint
        run: |
          echo ""
          echo "🏃‍♂️ Running swiftlint on modified files 🤵‍♂️"

          swiftlint --version

          git diff origin/main --name-only --diff-filter=AMCR \
            | grep -E "\.swift\$$"                            \
            || echo "No files added nor modified!"

          git diff origin/main --name-only --diff-filter=AMCR \
            | grep -E "\.swift\$$"                            \
            | xargs --no-run-if-empty swiftlint lint --quiet --reporter github-actions-logging
