# Leka - iOS Monorepo
# Copyright APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Linter - pre-commit hooks

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre_commit_hooks:
    name: pre-commit hooks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        files: [changed_files, all_files]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          lfs: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install -r requirements.txt
          python -m pip freeze --local

      - name: Install tools
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew update && brew bundle
          npm install -g
          pre-commit install
          pre-commit autoupdate

      - name: Cache python
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre_commit_hooks-${{ env.pythonLocation }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit hooks --all-files
        if: matrix.files == 'all_files'
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Run pre-commit hooks --files
        if: matrix.files == 'changed_files'
        run: |
          pre-commit run --show-diff-on-failure --color=always --files $(git diff --name-only -r HEAD^1 HEAD --diff-filter=AMCR)
