# Leka - iOS Monorepo
# Copyright APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Linter - SwiftFormat

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.swift"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: swiftformat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: false

      - name: Install SwiftFormat
        run: |
          brew install swiftformat
          swiftformat --version

      - name: Run swiftformat
        run: |
          swiftformat --lint --reporter github-actions-log .
