# Leka - iOS Monorepo
# Copyright APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Linter - hk hooks

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hk:
    name: hk hooks
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        files: [changed_files, all_files]
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
          lfs: false

      - name: Set up mise
        uses: jdx/mise-action@v3
        with:
          version: 2026.1.5
          install: true
          cache: true
          cache_key: "mise-{{platform}}-{{file_hash}}"

      - name: Install tools
        run: |
          npm install -g ajv-cli
          uv sync --frozen
          hk --version
          uv --version
          python --version

      - name: Run hk hooks --all-files
        if: matrix.files == 'all_files'
        run: |
          hk run pre-commit --all

      - name: Run hk hooks --changed-files
        if: matrix.files == 'changed_files'
        run: |
          hk run pre-commit --from-ref HEAD^1 --to-ref HEAD
