# Leka - iOS Monorepo
# Copyright APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Linter - pre-commit hooks

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: pre-commit hooks
    runs-on: [self-hosted, iOS]
    strategy:
      fail-fast: false
      matrix:
        files: [changed_files, all_files]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          lfs: true

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ runner.name }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-${{ runner.name }}-
            ${{ runner.os }}-pre-commit-

      - name: Run pre-commit hooks --all-files
        if: matrix.files == 'all_files'
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files
          pre-commit gc

      - name: Run pre-commit hooks --files
        if: matrix.files == 'changed_files'
        run: |
          pre-commit run --show-diff-on-failure --color=always --files $(git diff --name-only -r HEAD^1 HEAD)
