# Leka - iOS Monorepo
# Copyright APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Linter - SwiftFormat

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.swift"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: swiftformat
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        files: [changed_files, all_files]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          lfs: false

      - name: Setup brew
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Install SwiftFormat
        run: |
          brew update && brew bundle

      - name: Run swiftformat on ${{ matrix.files }}
        if: matrix.files == 'all_files'
        run: |
          swiftformat --lint --reporter github-actions-log .

      - name: Run swiftformat on ${{ matrix.files }}
        if: matrix.files == 'changed_files'
        run: |
          git diff origin/main --name-only --diff-filter=AMCR \
          | grep -E "\.swift\$$"                              \
          || echo "No files added nor modified!"

          git diff origin/main --name-only --diff-filter=AMCR \
            | grep -E "\.swift\$$"                            \
            | xargs --no-run-if-empty swiftformat --lint --reporter github-actions-log
