# Leka - iOS Monorepo
# Copyright 2023 APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Tuist - Main Cache Warm

on:
  push:
    branches:
      - main

jobs:
  cache_warm:
    name: cache warm
    runs-on: [self-hosted, iOS]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 # Fetch all history for all branches and tags

      - name: Run tuist cache warm
        run: |
          tuist fetch
          tuist cache warm
          tuist generate -n
