# Leka - iOS Monorepo
# Copyright APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Tuist - Build

on:
  push:
    branches:
      - develop
    paths:
      - "**/*.swift"
      - ".mise.toml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.swift"
      - ".mise.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TUIST_TURN_OFF_LINTERS: TRUE
  TUIST_GENERATE_EXAMPLE_TARGETS: TRUE
  TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG: FALSE

jobs:
  build:
    name: build
    runs-on: [self-hosted, iOS]
    strategy:
      fail-fast: false
      matrix:
        TUIST_DEVELOPER_MODE: [TRUE, FALSE]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # shallow clone
          lfs: true

      - name: Setup mise
        run: |
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          mise install

      - name: tuist install
        run: |
          TUIST_TURN_OFF_LINTERS=${{ env.TUIST_TURN_OFF_LINTERS }} \
          TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
          TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG=${{ env.TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG }} \
          TUIST_DEVELOPER_MODE=${{ matrix.TUIST_DEVELOPER_MODE }} \
          tuist install

      - name: tuist generate
        run: |
          TUIST_TURN_OFF_LINTERS=${{ env.TUIST_TURN_OFF_LINTERS }} \
          TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
          TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG=${{ env.TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG }} \
          TUIST_DEVELOPER_MODE=${{ matrix.TUIST_DEVELOPER_MODE }} \
          tuist generate --no-open

      - name: tuist build
        run: |
          TUIST_TURN_OFF_LINTERS=${{ env.TUIST_TURN_OFF_LINTERS }} \
          TUIST_GENERATE_EXAMPLE_TARGETS=${{ env.TUIST_GENERATE_EXAMPLE_TARGETS }} \
          TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG=${{ env.TUIST_GENERATE_MODULES_AS_FRAMEWORKS_FOR_DEBUG }} \
          TUIST_DEVELOPER_MODE=${{ matrix.TUIST_DEVELOPER_MODE }} \
          tuist build
