# Leka - iOS Monorepo
# Copyright 2023 APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Tuist - Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: [self-hosted, iOS]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 # shallow clone

      - name: tuist fetch
        run: |
          tuist fetch

      - name: tuist cache warm
        run: |
          tuist cache warm -x

      - name: tuist generate
        run: |
          tuist generate -x -n

      - name: tuist build
        run: |
          tuist build
