# Leka - iOS Monorepo
# Copyright 2023 APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Tuist - Clean

on:
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clean:
    if: ${{ github.event.label.name == 'tuist:clean' }}
    name: clean
    runs-on: [self-hosted, iOS]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 # shallow clone
          lfs: true

      - name: tuist clean
        run: |
          tuist clean

      - name: Delete Xcode derived data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: remove label
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'tuist:clean'
            })
